image: ghcr.io/conda/conda-ci:main-linux-python3.9
tasks:
  - name: initialize
    init: |
      mkdir -p .vscode
      echo '{"python.pythonPath": "/opt/conda/bin/python"}' > .vscode/settings.json
      eval "$(sudo /opt/conda/bin/python -m conda init bash)"
    command: |
      eval "$(sudo /opt/conda/bin/python -m conda init bash)"

vscode:
  extensions:
    - eamodio.gitlens
    - ms-python.python
    - ms-python.vscode-pylance
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
#     - oderwat.indent-rainbow # Highlight indentation level
