image: continuumio/miniconda3
tasks:
  - name: initialize
    init: |
      mkdir -p .vscode
      echo '{"python.pythonPath": "/opt/conda/bin/python"}' > .vscode/settings.json
    command: |
      conda init && source ~/.bashrc

vscode:
  extensions:
    - ms-python.debugpy
    - eamodio.gitlens
    - ms-python.python
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
